INSERT INTO `jxs0_category` VALUES('1','1','content','1','0','0','0','0','1','关于杨氏','','','','','about','http://192.168.1.100/jxs0/index.php?m=content&c=index&a=lists&catid=1','0','0','array (
  \'ishtml\' => \'0\',
  \'template_list\' => \'\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'\',
  \'repeatchargedays\' => \'1\',
)','1','1','0','guanyuyangshi','');
INSERT INTO `jxs0_category` VALUES('2','1','content','1','0','0','0','0','2','企业荣誉','','','','','honor','http://192.168.1.100/jxs0/index.php?m=content&c=index&a=lists&catid=2','0','0','array (
  \'ishtml\' => \'0\',
  \'template_list\' => \'\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'\',
  \'repeatchargedays\' => \'1\',
)','2','1','0','qiyerongyu','');
INSERT INTO `jxs0_category` VALUES('3','1','content','0','1','0','0','0','3','新闻中心','','','','','news','http://192.168.1.100/jxs0/index.php?m=content&c=index&a=lists&catid=3','0','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'default\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','3','1','0','xinwenzhongxin','');
